/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ElectricidadRouteImport } from './routes/electricidad'
import { Route as AlbanileriaRouteImport } from './routes/albanileria'
import { Route as AireAcondicionadoRouteImport } from './routes/aire-acondicionado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'

const ElectricidadRoute = ElectricidadRouteImport.update({
  id: '/electricidad',
  path: '/electricidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbanileriaRoute = AlbanileriaRouteImport.update({
  id: '/albanileria',
  path: '/albanileria',
  getParentRoute: () => rootRouteImport,
} as any)
const AireAcondicionadoRoute = AireAcondicionadoRouteImport.update({
  id: '/aire-acondicionado',
  path: '/aire-acondicionado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aire-acondicionado': typeof AireAcondicionadoRoute
  '/albanileria': typeof AlbanileriaRoute
  '/electricidad': typeof ElectricidadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aire-acondicionado': typeof AireAcondicionadoRoute
  '/albanileria': typeof AlbanileriaRoute
  '/electricidad': typeof ElectricidadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aire-acondicionado': typeof AireAcondicionadoRoute
  '/albanileria': typeof AlbanileriaRoute
  '/electricidad': typeof ElectricidadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aire-acondicionado'
    | '/albanileria'
    | '/electricidad'
    | '/api/chat'
    | '/api/public/lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aire-acondicionado'
    | '/albanileria'
    | '/electricidad'
    | '/api/chat'
    | '/api/public/lead'
  id:
    | '__root__'
    | '/'
    | '/aire-acondicionado'
    | '/albanileria'
    | '/electricidad'
    | '/api/chat'
    | '/api/public/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AireAcondicionadoRoute: typeof AireAcondicionadoRoute
  AlbanileriaRoute: typeof AlbanileriaRoute
  ElectricidadRoute: typeof ElectricidadRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/electricidad': {
      id: '/electricidad'
      path: '/electricidad'
      fullPath: '/electricidad'
      preLoaderRoute: typeof ElectricidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albanileria': {
      id: '/albanileria'
      path: '/albanileria'
      fullPath: '/albanileria'
      preLoaderRoute: typeof AlbanileriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aire-acondicionado': {
      id: '/aire-acondicionado'
      path: '/aire-acondicionado'
      fullPath: '/aire-acondicionado'
      preLoaderRoute: typeof AireAcondicionadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AireAcondicionadoRoute: AireAcondicionadoRoute,
  AlbanileriaRoute: AlbanileriaRoute,
  ElectricidadRoute: ElectricidadRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
